####################################################################################################################################################################################### Mind control

label control1:
    "[d] looks at [p]. His eye turns red"
    d "..."
    d "(Not working!)"
    $controlStage = 1
    jump sim
    
label control2:
    "[d] looks at [p]. His eye turns red"
    "[p] touch his chest."
    p "..m.."
    p "(What just happens?)"
    d "(I have reached into his mind but the barrier is too strong. Have to break him more)"
    $controlStage = 2
    jump sim
    
label control3:
    hide screen day
    hide screen stat
    "[d] looks at [p]. [p] scares. He quickly looks away. [d] chuckles"
    d "So you have know to fear me huh?"
    p "...N-..."
    p "......"
    "[d] smirks. His eyes turn red."
    d "Look at me!"
    "[p] looks at [d]. He feels dizzy, like someone penetrate his brain"
    p "Ngh..."
    "The vines release [p]"
    p "..."
    d "What are you doing? On your four and crawl here!"
    "[p] feels like his body moves against his will."
    p "Mnh..."
    d "(I cannot stop moving...)"
    "[d] touches his face. [p] feels hot. [d]'s touch somehow become really pleasant."
    scene fin_touch
    p "Ngh!"
    d "Good boy. If you were to obedient like that from the start, I would have treat you better."
    p "(My head. It hurts!)"
    d "Suck this!"
    scene fin_mouthb
    p "MNGH!"
    "[d]'s thumb thrust in [p]'s throat. It's painful, but feel good at the same time."
    p "Ngh..."
    scene darkforest
    "[d] takes his hand out of [p]'s mouth and moves to his chin."
    p "?"
    "[d] kisses [p]'s forehead."
    p "!"
    p "...."
    "He pushes [p] to the ground. [p] daze."
    scene deepimpact_head
    "[d] grasps [p]'s legs and start to put his dick in." 
    p "Mgh!"
    p "...Agh!"
    d "What a sweet sound!"
    p "Ahhh...Ahhh..."
    "[p] doesn't react or curse [d]. He lets [d] does whatever he want to his body."
    p "..M...ngh..."
    "[d] enters [p]'s agnus slowly."
    p "...Ngh..."
    p "...[d]...m..."
    "Despite [p] prepared for the pain, [d] tenderly press his dick in."
    "Each time [d] enters him, he feels like he was in heaven. The warmth of [d] cock, his movement, his touch. Everything turns [p] on."
    p "..M...n..."
    p "...Arghhh..."
    d "You act rather cute today."
    p "...Ngh....m...aah..."
    d "You twitch a lot [p]. You like it don't you?"
    "Ater [p] gets use to it, [d] slams [p] faster and stronger."
    scene deepimpact_deep
    p "..N...ngh...no..no I don't...ahhh.."
    "[p] cries. It's normal for him to burst his tears while having sex with [d] because it hurts a lot. However, right now, it was tears of shame."
    d "Why are you crying? Is it too good?"
    p "..."
    p "..ahh...haaa..."
    d "Hey, say something!"
    p "...mgh..."
    p "P-please [d]. I cannot take it anymore. St-.. mgh!"
    scene deepimpact_deepcum
    p "AGH!..."
    p "Ngh! P-please st-"
    scene deepimpact_deep
    p "N...mgh!...Take it out...please...I can't-...ahh"
    d "You must feel really good right now. I keep on hitting your sensitive spot."
    p "...ngh! Ahh..."
    d "Only I can make you feel this good."
    p "...[d]...P-please stop..."
    "[d] smirks. He doesn't response nor stop."
    p "N-no, please. Have you had enough entertainment?"
    p "Is that enough? I'm sorry for what I did to you. I'm begging you. Please let me go! I'm going insane!"
    d "..."
    p "[d]. Please stop. Have pity on me. My mind is breaking apart."
    "[p] cries harder. He makes it look like the world had come to an end."
    p "P-Please stop. Please let me go."
    d "..."
    scene darkforest
    "[d] stops"
    d "You make my dick goes soft [p]. How do you plan to compensate for that?"
    p "I-I'm sorry."
    d "Since you have become so pitiful, I'll give you a chance."
    p "!"
    d "I need to pee right now. And your mouth will be the toilet. If you do this well, I'll not tie you anymore."
    "[p] eyes lighten up."
    p "R-really? You will let me go?"
    "[d] smirk."
    p "..."
    p "W-will you really keep your work?"
    "[d] climbs on top of him."
    menu:
        "Peep":
            scene peep_close
            show peep_cry
            "[d] peeps in [p]'s mouth"
            p "Ngmm...mhn..."
            scene peep
            show peep_nocry
            p "...nhh..."
            d "Stop spilling it out!"
            p "Mn...n..."
            scene peep_chew
            show peep_cry
            "Its hotness and stinkiness makes [p] dizzy. It tastes was horrible. Much worse than when [d] forced him to drink his own piss."
            p "M...h..."
            scene peep_inmouth with vpunch
            d "Ngh..."
            d "Is it hot?"
            p "Mgh...m..."
            d "You are so useless. Cannot even be a proper toilet."
            p "Mnn...ngh...h..."
            d "You keep spill my piss out and dirty me no matter what I do."
            p "Ngh...h..."
            scene darkforest
            "[d] kisses [p]'s head again"
            p "Ngh..."
        "Smirks and go away":
            "[d] smirks and pulls his trouser on."
            "[p] nervously looks at [d]."
        
    d "I'm keeping my words. Pitchy had more important job to do anyway."
    p "C-can I go now?"
    d "Of course."
    "[p] smiles."
    d "12 feets."
    p "?"
    d "From that tree, you can freely move around 12 feet."
    d "If you move more than that without my permission, don't blame me for your punishment."
    d "You know that even without being tied up, you cannot escape."
    "[p] was shocked. Then he becomes despress."
    "It was very stupid of him. There is no way [d] lets him go with just a simple request that he can force [p] to take anytime. He will rotten here till the day he dies."
    "[p] gets up and sits under a tree, hugs his knees. His head tucks between them."
    d "Not being impulsive anymore huh? Your emotion seems to be more stable these days [p]."
    p "..."
    "[p] trembles. He hugs his knees tighter, which makes him look even smaller."
    p "..."
    d "..."
    "[d] goes away."
    $controlStage = 3
    jump sim

label control4_ques:
    $controlStage = 4
    scene darkforest
    "[d] touches [p]'s cheek while he were sleeping"
    p "Uhm..."
    d "Walkup"
    p "..."
    d "Hmph"
    "[d] brutaly slaps [p]. [p] knocked down to the ground" with vpunch
    scene control4_slap
    "Not understand what's happen, he consfuses and tries to get up"
    p "Wh-!" 
    scene control4_stomp with vpunch
    "[d] stomps on his head" with hpunch
    p "Hph!"
    p "What are y-"
    p "!"
    "[d] brutally stomps on [p]'s head again" with vpunch
    p "M...Aa..."
    scene control4_whisper
    "[d] climb on top of him and whisper."
    d "When have you become so defenless. Aren't knight suppose to keep one eye open when sleep?"
    p "T-Tha-...I'm tired...Y-yo-"
    scene control4_lickear
    "[d] licks [p]'s ear hole"
    d "Or you have give up becoming a knight and choose to be a bitch instead?"
    p "Mgh..."
    "[p] heard some noises. The mosquito monsters appeared from the bush. [d] get away from him."
    scene control4_slap
    p "[d] [d]"
    scene darkforest
    show m_surprise
    show m_beaten7 
    show m_m_sexclench1 
    show m_shame
    show m_blush
    show m_cockup
    show thunder at infinite_flash
    "The mosquito attach [p]" with hpunch
    p "AGHHH! AAAAGGGGHHH!"
    p "[d]! [d]!"
    d "Hahaha, is it that hard to control your own urine? I can see some stool too"
    p "...W-Wh..?"
    "[p] unable to move his mouth and body."
    scene darkforest
    "[d] throws a heavy kick on [p]'s head" with vpunch
    p "Mgh!"
    "He stomps on his head again." with hpunch
    scene control4_stomp
    d "I own you. I can beat you for no reason whenever I want. That's why!"
    p "F-fu..."
    scene control4_stomp_cries
    "[p] cries"
    d "Cries again? Had you become meek? Or you cannot take it anymore? What a weakling, trying to play tough."
    scene darkforest
    p "Bastard!"
    "Recovered, [p] rushes to [d] but falls. He still paralyzed. [d] laughs." with vpunch
    d "Finished taking your shit first. Don't attack me while poping"
    p "F-Fuck you! I'm not!"
    "[p] rushed to [d], punches him in the face repeatedly. He didn't avoid." with hpunch
    d "..."
    p "FUck you! Listen or don't, you treat me the same. Yet, yet I believe and humiliate myself to amuse you"
    "[d] kicks [p]. [p] uses both hands to block it. He had to jump backward to neutrolize the kick to not fall." with vpunch
    d "At least at that time, aren't you able to escape the pain?"
    p "HAAAAAHHHHH!!"
    "[p] rushes to [d] immediately. His punches become stronger and faster. [d] steps backward and avoid the hit as [p] rushes in." with hpunch
    d "When we first met, I didn't pay attention, but is this really how you always fight?" 
    "[d] reaches his hand and touches [p]'s forhead with his index finger. [p] steps back then rushes in again and throws heavy punches as [d] avoid them easily" with vpunch
    d "Your moves are predictable. Your reflexness is subpar. You cannot react quickly enough."
    p "FUCK! SHUT UP!" with hpunch
    "He uses more strength and moves faster. Because of that, each time [d] avoid, it cost [p] a longer time to re-position and throws another punch." with vpunch
    d "No wonder people said you are blood-thrist. You cannot afford to spare enermies, nor even looking out for other people." 
    d "Fight long enough and anyone can guess your next action. One suprise attack from the back and you are gone."
    p "SHUT YOUR MOUTH UP!!" with hpunch
    "[d] catches the punch and breaks his arm" with vpunch
    p "AGGHHHHHHH!"with hpunch
    p "Haa...haa..."
    d "It breaks just with that strength. Your bones are not strong enough to be a warrior. Let alone killing monsters." 
    p "S-STOP!!"
    d "I have always amazed [p]. Are you really one of your country champion? It's must be a very small country, with full of weaklings." 
    d "How can you supass The Flow thresold is beyong my understading. It's a miracle that your strength and agility reached this level. But this is your limit."
    p "S-Shit! I said stop!!!"
    "[p] escapes [d] and throws him a kick" with hpunch
    "[d] breaks [p]'s leg" with vpunch
    p "AAAAGGGGHHHH!"
    "[d] throws [p] to the ground" with hpunch
    d "It must be normal when you are born. But the more you grow up, the more you train and improve, the more the world turns its back on you. You already notice this right?"
    p "S-STOP! JUST SHUT UP!!!"
    p "Haaa...haaa...Shu- u-... haaa..."
    "[p] tries to stands up"
    p "Uhm..N!"
    d "Even though you are just like a fly to The Flow... what a tragedy. " 
    d "Don't blame me. Even if it's not me, you will eventually die painfully."
    p "Ha..haa..."
    "[p] glance at [d] hatefully."
    d "..."
    p "Haa...ugh! S-shit! If I not run into you...If I have The Stone...The Stone will... haa..haaa..."
    "[d] laughs"
    d "The existents that is able the bend the rules God created have to be in ultimate harmony with it. Only the creations chosen by The Flow can use The Stone"
    d "Do you know what existent The Stone hate the most? You. Your kind." 
    d "The moment you touch The Stone, either it or you will be destroyed. You are clutching at a straw [p]."
    p "No. You are lying."
    "[d] smiles"
    d "I said that to you as the Creature of the Day, one of the three oldest creation of God that is born to project The Flow and The First Stone. So that this world will keep on living."
    p "Even if this world is pushing me away, am I not a living being? Am I not worthy to be treated like one?" 
    d "..."
    p "Why? Who give you the right to hurt me and trample on my sanity like this? Does God not need moral? Does God not need to follow rules?"
    d "No." 
    d "But then aren't you just doing the same? How many monsters and criminals had you torture to death? Aren't they living being too? Aren't they worthy to be treated like one?"
    "[p] was shocked. He had never think about that. After been through too much wars and saw what they do to the captured soldiers, [p] makes a habit of torture them as a stress relief." 
    "If what he did was normal, then what [d] did to him was normal too. Now, he is just in the same position as them, and [d] is replacing his role as the toturer."
    "He totures them by inflicting extreme pain then kill them off. [d] totures him by inflicting pain, humilation and fucking him. He asked for justice, but aren't he and [d] just two sides of the same coin?"
    p "Monsters and criminals...are living beings..."

    "[p] turns his head away. [d] grasps his face and turns it back."
    d "Look at me [p]!"
    p "..."
    "[d]'s eyes turn red. Again, [p] feels like his head was penetrated. [d] thrusts his hand into [p]'s head, then his brain"
    p "Ughh...aaa..."
    "The pain were too much that [p] cannot even scream. [d]'s fingers go on deeper and deeper. With each thrust, [p] feels like thousands of needle attach his brain"
    d "Hmp, I think this is the sexual part of the brain"
    p "Mmm...mngh...m..."
    "[p] cock hard on its own and cum. How much [d] want him to suffer before killing him off?"
    "[d] keeps on penetrade deep in the sexual part of the brain. [p] pain was lessen and replace by plessure"
    p "Gah...ah...a..."
    "[d]'s other hand grasps [p] shoulder's hard."
    d "Don't fight, got it? It will just makes things harder for you."
    "All 5 fingers of [d] had penetrate to the deepest part of [p]'s brain. [d] feels a flow of energy comming in. It comes faster and heavier each second."
    p "Ngh!"
    d "Ngh!"
    "[p] becomes unconscious"
    d "[p], [p]"
    p "Ngh!"
    "[d] shakes his head. He tries to be awake but also fallen as sleep. While still consious, he wraps his hand around [p]."
    
    "The next morning, [p] wakes up."
    p "Am I still alive? I can't even feel myself"
    "He reaches his arms and legs, but they are heavier than usual, like they had some root connected to the Earth. He was unable to move, like a tree."
    p "Shit! What the fuck is going on?"
    "[p] remembered all the things [d] did to him yesterday"
    p "Since the begining, he tries to weaken my will. And yesterday...yesterday, he goes deep into my mind, I was unable to fight it. He alters me."
    "[p] heard hand claps"
    d "You guess right [p], you had become smarter. A five year old kid could have the same conclusion as you, only faster."
    p "[D]! FUCKER! WHat Have You Done?"
    d "Manners. Should I teach you again by pressing my cock into that tiny hole?"
    p "..."
    p "Just kill me! What did you turn me into?"
    d "You won't die. You have become an immortal, just like me."
    p "!"
    d "You are no longer disrubt The Flow of this Earth. It won't push you away."
    p "No, this can't be happening"
    d "The only drawback is your arms and legs are the Earth, you cannot move for now. But it's a cheap price right? Beside, your 2 slutty holes is till easily accessible"
    p "[d]! YOU BASTARD!"
    "The ground moving faster and faster, [p]'s arms and legs cracks. He consumes the Earth and get his new arms and legs"
    d "Not bad."
    "[p] thurst to [d], about to attack him. [d] calls thousands of spikes formed from the ground and shoot at [p]. An explosion, dust flying everywhere"
    "[p] disspeared."
    d "You have plan to escape from the start huh. It seems like you have become more mature."
    "[p] runs. He doesn't know where did he runs to. He just run forward"
    p "([d] didn't able to catch me. It seems like he had become weaker. Is it because of the thing he did to me?)"
    p "Water sounds"
    "He turns and runs to a waterfalls. The demon said to him there is only one river here. The Stone is either top, or down"
    "He looks at himself in the river and kneels down"
    p "That fucker, why did he hate me so much. So disgusting" 
    p "I should have killed myself the moment he captured me. I wanted to live that time. I accepted all the humiliation and let him trambled all over me"
    "[p] doesn't know which word of the monster is true. He can tried to get out of this forest, or find the stone"
    p "Even if I can get out, he will still find me. If he captured me again, I can no longer escape. He will beat me like an animal and fuck me like a whore whenever he likes." 
    p "He will force me to beg and do all the disgraceful things till my mind scatter to pieces."

    "[p] heard a foot step"
    p "Who?"
    n "Mr.Knight? What happen to you?"
    p "You!"
    "[p] grasp [n]'s shoulder"
    p "Where is the stone? Is it upstream or down stream?"
    n "I-It's downstream"
    "[p] looks behind him"
    p "So it's this way"
    n "..."
    p "What if I can't find it?"
    "[p] grasp [n]'s shoulder hard"
    p "Go with me!"
    n "No, I -"
    "[p] carries him and run like flying"
    n "It's there"
    p "I didn't see anything"
    n "In the middle of the river, there's a temple"
    "[p] tries to look, but it just all water"
    p "Guide me, I cannot see a thing"
    n "Right now! Go to the middle of the river"
    "[p] form the ground into a bridge"
    n "That's sir [d]'s power..."
    p "!"
    p "I can see it now. We have to hurry!"
    scene temple 
    "[p] can sense that [d] is really close"
    p "Where Is The Stone?"
    n "Ah! Up there, on the status hands"
    p "!"
    n "!"
    d "What do we have here? A half-ass monster and a demon"
    "[d] steps closer to [p] and [n], his footsteps become louder"
    "[p] jumps to the statue hands"
    d "Running away?"
    "A big hand slaps [p] to the ground"
    p "Mgh!"
    "[p] forms the ground to a giant hand and attacks [d]. [d] negates it. The hand turns into dust."
    d "!"
    "[p] jumps to the status' hands. [d] destroy the status, [p] falls to the ground."
    p "Ugh!"
    "The Stone falls to [d]'s place"
    p "..."
    n "Ahh!"
    "A column falls onto [n]. With a swift moment, [p] pushes him away. Both fall to the ground"
    p "Kuh"
    "[p] stands on 1 knee. [d] kicks the stone to [p]"
    p "..."
    d "It just a rock I put it there 300 years ago"
    "[p] touches the stone and crush it"
    p "It holds no power. Is The Stone just a lie God make up?"
    d "No. You are closer to it than you think"
    p "..."
    d "How about we make a bet?"
    p "What is it?"
    d "I show you where The Stone is. If you can get it or use it, I'll not touch you anymore. If not, you know what comes next"
    p "Where is the stone?"
    "[d] points toward [n]"
    p "Impossible. What kind of joke is this?"
    d "He should have died a long time ago, in a masscar between human and demon that takes place right here, in this temple." 
    d "The Stone saves him, a newborn child, and I put it inside his body as its will. Hard to believe huh?"
    "[d] eyes turn red. [p] can see the stone inside of [n]"
    p "..."
    "[p] penetrates his hand into [n]'s chest"
    n "Ahhh...Sir.Knight, p-please..."
    p "Ahhh...Arghhh..."
    d "The energy born from yours and the stone contacting each other will kill [n] first"
    p "Ahhhh...Arghh...."
    n "S-sir Kni- pleas-..."
    "[p] had pass the outter barrier"
    n "Ahh...Ughhh...ahhh..."
    p "Ahhhh...Arghhh....."
    p "[n]! If you don't want to die. Use its power. Either kill me, [d], or both of us. This is a fair game. I'm not gonna hold back"
    n "N-no. Please stop. I won't. I won't .... ahhhhh..."
    "[p] almost the inner barrier"
    p "Arghhh...Arghhh..."
    p "(It's your false to not participate in this life and death game. Sorry)"
    "[p] remmembered the time the demon help him to get water, and his worried expression when he turns into a monster." 
    "The demon not once was afraid of him. He offers help and got his life taken away by the one he helped in return"
    "The very first reason [p] wants to become strong was to lesser his father burdern. The second reason was to make his country stronger and everyone lifes better. The third reason was to protect his dad, brother, and people he cares"
    "He doesn't know when or why things turn out this way. His country feared him, his father hated him and his brother pity him. Since when did he drop his humility and kill his opponents mercilessly?"
    "[p] cries. He puts his hand out of Nine's chest"
    n "Ahhh...haa...ahhh..."
    n "ahh..S-sir. Kni-.."
    "[p] punches [n]"
    n "Mgh!"
    p "Go away! If I ever see your face again, I'll kill you!!"
    n "...."
    "[n] runs away"
    "[d] comes closer as [p] crawing on the ground and clenches his fists."
    p "..."
    p "I lost. What do you want to do with me?"
    d "What do you think?"
    p "Stop that already. Didn't you said I'm a birdbrain? How can I know what a genius like you think?"
    jump badend




label badend:
    d "This is the first time you have flatten me like that. But it won't lessen your punishment."
    "[p] smirks turns away. He looks like an empty shell."
    "[p] puts his hand around his neck and started to strangle it."
    p "H...M..."
    "[d] grasps [p]'s hand and tears his chest, where his heart is. His graps are so strong that [p]'s chest bleed."
    p "Ugh!"
    d "Listen and remember this well. Whatever wounds you have, you won't die. Even if my power were to taken away, you still won't die. You just can't move, and all your fatal wounds remain."
    "[d] cough."
    p "Hahaha. What a useless thing to do. You've gained nothing from me but curses. I, in the other hand, can sense that your power is decreasing. And it seems like it won't come back."
    d "..."
    p "You are so smart huh? Sharing your power to your most hateful enermy." 
    p "I can see it now, why you called yourself by the other name, and your weird timing. Should I spread it out to every creatures, your weakness?"
    d "..."
    p "Why the silent?"
    "[d] kicks [p] to the ground" with hpunch
    p "Mgh!"
    d "When you are unhappy, you sure bark and scratch a lot. What should I do to bring my dog joy? Ah, how about reunite with your family?"
    p "Don't you dare-"
    d "Huh? Is there any monster living here?"
    "Some noises coming from the ground."
    p "..."
    p "W-what th-!"
    "[d] smirks. He grasps [p]'s hair and pins him there while he tries to standup."
    p "N-no....AAAAGGGGGHHHHHHHHH....."
    " "
    scene darkforest
    "[ri] castle, in a meeting with dozens of dukes, duches, followers and generals"
    h "[k], there's a monster said he knows prince [p] where about. He also want to give you a present. We have our men circle around him."
    ren "A monster? But he knows brother whereabout."
    k "Tell him to get out! If he doesn't comply, kill him!"
    ren "But dad!"
    "There are screams outside the door. [d] walks in with some monsters. They were carrying a cart with a big box."
    d "Dear [k], lord of the Holy Land, we know your belove son whereabout."
    k "Guards, kill them!"
    "Guards and the Generals attacks the monsters. But they are no match."
    ren "What did you do to my brother?"
    d "You don't have to worry about that."
    k "!"
    d "Because he is right here!"
    show present
    "[d] pull the ribbons out" with hpunch
    p "Mgh! Ngh!"
    "The boxes break into 4 pieces, [p] was lying in there, suffering. His mouth and ass constantly penetrated by some kind of insect monster"
    ren "Borther!"
    h "Prince [p]!"
    "The insect shock [p]."
    p "UUHHMMMM...UHMMMM..."
    p "Uhmm...uhmp..."
    "A monster pushes him to the ground" with vpunch
    p "Uhh...ahhh..."
    "The insects get out of [p]. They have suck almost all of [p]'s energy and that hard push annoyed them."
    show present_push
    "No energy to control himself, [p] peep on the ground."
    d "Hahaha, look at you. Cannot control your urine again."
    "The monster wipes his pee and insert that finger into his mouth"
    show present_feedpee
    d "Suck it!"
    p "Uhm..."
    "The prince sucks [d]'s finger!"
    ren "Brother!"
    p "!"
    k "[ren]! Stop! Becareful of those insect monsters."
    d "That's right prince [ren], you father was right. These are rare but famous and dangerous creatures that like to host on warm body and never want to let it goes. "
    d "They will fuck you first then suck your energy, release nerve damage poison and aphrodisiac, shock electric, lay eggs. Finally, when the host dead, their babies get out."
    ren "No! Brother!"
    d "Don't worry, unlike you, your brother won't die... Because I had turn him into an immortal monster. Whatever type of treatments he had, he won't die."
    ren "You are lying!"
    k "Get out [ren]!"
    d "Don't chase him out. There are more monsters outside"
    k "..."
    k "What do you want us to do? Creature of the Dark Forest never went outside. If it is because of [p], it is his problems. He is not a human or even a citizen here"
    p "..."
    d "Did you hear that [p]? Your dad chases you out"
    p "..."
    "[d] holds [p]'s chin and hands. He pushes him forward, facing the king."
    show present_king
    d "Don't you want to beg him to keep you? Or at least say hi, told him that you are happy to see him."
    p "..."
    d "Say it, don't be shy."
    p "..."
    d "Huh?"
    p "D-dad. I-it's nice to see you again."
    k "Please bring him out, together with all your monsters"
    d "What do I do? I already promise him to let him sit on the throne"
    h "Prince [p] make a deal with that monster?"
    
    d "Hey you!"
    h "Y-Yes sir!"
    d "Chain this dog and walk him around the city!"
    h "Yes sir!"
    "[p] quietly let the servant chain him. He crawls on four, like a dog."
    d "He's your pet now. Do whatever you want with him"
    h "T-Thank you!"
    "The servant pats [p] head."
    h "Let's enjoy our time, dog."
    "[p] says nothing and lets the servant do what ever he please."
    scene castle_pet
    "[d] smirks"
    d "Since you are docile right now. I'll give you a gift."
    p  "..."
    d "Do you want your family to escort you outside or do you want me to chase them out?"
    p "Please chase them out, far far away from here..."
    p "to..."
    "[p] glance at [d], observes his expression."
    p "...to another country."
    d "You heard that [k], gather everyone, told them you were dethrone. Now, this country is mine."
    k "No, you can't..."
    d "If you do it well, no one will suffer greatly. Else, I'll told my friends to do whatever they want."
    k "I-I uderstand."
    k "..."
    k "Please...don't kill him..."
    "The king goes away without looking at [p]. He told the mages to prepare the magical sky screen for the announcement."
    p "..."
    "[d] smirks."
    d "Only ask for that huh. At least he understand the situation, unlike someone."
    p "..."
    d "You don't look too happy [p]. How about visiting the citizens. Let see how the citizens of this fallen country will welcome their slave prince."
    "[p] was shocked. Meeting them right now, as a betrayal, in this state, is the last thing he wanted"
    d "Told the citizen I gave them permission to do whatever they want aside from killing him."
    h "Yes sir!"
    "The servant holds the lease forward."
    h "Move fast!"
    "[p]'s didn't hear what the servant said."
    p "[d]..."
    "[d] looks at the servant. The servant put a gag inside his mouth"
    p "Umm...n"
    h "Dog doesn't talk human language. Now move!"
    "[p] doesn't move an inch."
    
    scene castle_whip
    "The servant whips him!" with hpunch
    p "Ugh!"
    h "I said move! Did you still think you are our prince after all this? You are nothing but trouble since the day you are born."
    p "U-uhm...n..."
    scene castle_poop
    "[p] shits himself"
    p "Ngm!"
    h "Gross!"
    "The servant pull [p]'s collar. They headed to the castle gate."

    "5 hours later."
    h "Prince [p] had come back!"
    scene gore_back
    d "..."
    "The servant had to hold [p] and pushed him in. [p] was in a critical condition." 
    "He was beaten and sratched from head to toe. Blood and sperm everywhere. His hands and legs was chopped off, his tongue is not there anymore." 
    "His eyes were taken away using a clean and neat technique"
    scene gore_back_hand
    p "U-u..a.."
    h "S-sir, you told me not to interfer"
    scene gore_back
    d "You did a good job!"
    p "N..."
    scene gore_back_ass
    p "U-u...a..."
    "[d] puts his finger into [p]'s ass"
    d "At least they keep the most valuable part of your body huh?"
    p "M...m u-..."
    d "I don't get what you are saying. If you can't speak, write it down."
    d "Oh, I forgot. You can't. Hahaha."
    p "Ua,...u-..."
    d "Someone put something in his mouth. It hurts my ears. If they cut the tongue, cut all the way, so there's no sound coming from him."
    scene gore_back_ass_sock
    p "Ugh..N!"
    p "Uh! Uh!"
    scene gore_back_sock
    p "U...n..."
    d "Throw him into a dog cage! Find a small one that fits his current body and makes he unable to move even an inch!"
    scene gore_cage
    "At night, [p] cries. He knows that his hands and legs can regenerate if he did right. But what about his eyes and tongue."
    "The things that he did to others finally comes back and bites him. Now, he cannot even kill himself. And if he can, he still won't die."
    "[p] tries, but he cannot uses the power."
    p "Hmp...ahh...mmm..."
    d "You look like a bitch in heat."
    "This is the second time [d] comes to [p] at night, beside the first time they meet."
    p "...m..."
    scene gore_cage_pull with vpunch
    "[d] opens the cage and pull [p]'s hair, drags him out of the cage."
    p "Ugh! U-A..."
    p "H..."
    "[d] lets go of him." with hpunch
    scene gore_pop with vpunch
    p "N...m..."
    d "You."
    "[p] shitting on the floor of the pet item storage room."
    d "So you have been holding it this hold time huh? That some disgusting stool. I wonder what did they feed you."
    "[p] clenches his whole body, tries to hold the shit in."
    p "U...Ngh..."
    scene gore_pop_pull with vpunch
    "[d] pulls [p]'s head and drags him." with hpunch
    "Hurt and scared, [p] pops even more. He even pisses himself" with vpunch
    p "U-a...n..."
    p "AA...a..."
    d "..."
    "[d] releases his hair and bend down. [p] clenches his teeth. He afraid [d] will hit him."
    "[d] carries him and put him to a pet bath"
    p "?"
    "[d] slashes water from the water storage basket to [p]. "
    p "!"
    "He aims directly at [p]'s ass to splash water"
    p "Ngh! U..."
    "At this point, [p] understands thaat [d] was trying to wash him." 
    scene gore_bath_finger
    "[d] spreads a few oak tree ashes into the water and takes a pinch of them, scatter his hands to washes [p]'s hair, neck, chest, back, armpit, then his cock and ass."
    p "U-a...ngh!"
    d "Hurt? Since this is a pet item storage room, there's only ashes. If it's too hard, I can get a black soap."
    "[p] shakes"
    d "No? Then what is it? Embrassing?"
    "[p] nodes"
    "[d] thrusts his finger deeper into [p]'s asshole."
    p "Ngh! N..."
    d "What is there to be shy about? There's no place in your body I haven't see. You stool and pee right before my eyes almost everyday."
    "Some tears fallen from [p]'s eyes."
    d "..."
    p "Uh!..Ugh..."
    d "What a pervert. You can even feel it in this situation."
    "[p] cries."
    d "You cried a lot these days [p]. You look cuter."
    "[d] intentionally hits on [p]'s protate again and again."
    p "Umm...Ngh..."
    p "U...a-...Ngh! M!"
    "[p] cums."
    p "Hm..n...ugh..."
    d "You cums just from fingering huh? It likes your sensation was enchance. Is that because your eyes was taken away?"
    "[p] cries"
    d "Now now, don't cry." 
    "[d] wipes [p]'s tears."
    d "Are you hungry?"
    "[p] nods."
    d "Thirsty?"
    "[p] nods."
    d "I bring your meal here."
    "[d] uses a towel to clean [p] and lets him sit on the ground"
    "[d] carries his head and gives him water."
    p "Ugh...uhn..."
    "[d] spoons feed [p]."
    p "...a..u.."
    d "What's wrong? Oh, Seems like your jaw got dislocate. It'll be painful to chew huh?"
    "[p] nods. [d] chews the food and feeds [p] by mouth."
    p "Hmm...hmmm..."
    "[d] kisses [p]."
    p "Umh! Uhm!"
    "The kiss becomes more passionate."
    p "Uhm...Ughm!"
    "[d] stops."
    d "Let put you back to the cage."
    p "Ua..u..! Aa.."
    "[d] puts [p] back to the cage and locks it. He puts in some water and food in the dog feeder."
    p "Ua..a...u..."
    d "What's wrong?"
    "[p] shakes his head."
    d "Ah, it'll be painfull for you to eat and drink by yourself since your jaw was dislocate."
    d "I'll comeback tommorow and feed you."
    p "Aa...! Au....u..."
    "[d] continues to lock [p] up in that cage for 3 months. Aside from him, no one was allowed to get in."
    "Unable to move, no sound to hear aside from [d] voices and footsteps drives [p] insane to the point being feeded, touched, fucked by [d] senselessly are what he waits for everyday."
    "[p] hears a noise. He knows that [d] is walking in. The door opened for a few minutes then closed."
    "He was waiting for [d] to step closer and get him out of the cage, but everything was silent."
    p "U...u.."
    "There was no response. [p] waits and waits but there is still no sound. No one was here. Was he hallucinating?"
    p "..."
    "He doesn't know how many days had passed since [d] not coming. Despite the pain, he eats and drinks in the dog feeder to survive."
    "Several days later, he heard footsteps and the sound of the opened door."
    p "A...u..."
    "[d] pulls him out of the dog cage and kisses him."
    p "Uaa...nhm..."
    "He kisses [d] back."
    d "You look more eager than usual. Do you missed me?"
    p "A..ua...a.."
    d "What does that mean?"
    "[p] nods his head."
    d "You really miss me? How cute!"
    "[p] can hear a sound of cloth smashing each other. The next thing he knows is [d] turns him around and penetrates him."
    p "M...A...Ua...h..."
    d "You feel it more today huh?"
    p "A....aua...."
    "[p] cum."
    p  "M...n..."
    d "After today, it'll took a week until I can get here again."
    p "U..a..."
    d "There was a lot of interesting things to do now I'm in charge of this castle."
    p "A...u..."
    "[p] presses his head into [d]'s chest. [d] careless his head."
    d "Do you want to come with me? I'll let you lie on the throne. I'll sit on your face, while everyone can see your cock and asshole."
    p "U...a...uaa..."
    d "What?"
    "[p] nods."
    d "Hahaha, are you that desparate? You make me want to cry now."
    "[p] presses his face in [d]'s chest harder and kisses it. [d] notices and touches his face."
    d "How about this prince? I will return your body to normal, make you king like you always wanted."
    d "In return, be docile and act cute. Listen and follow my every word, as if I'm your God."
    p "A...a..."
    "[p] nods."
    "[d] stands up, creates an energy sphere and pushes it to [p]. His whole body glow up and returns to normal."
    p "A..."
    "He looks around with his eyes, holds his throat, touches his arms and legs."
    p "A...haha..."
    "[p] cries. He covers his face with his 2 hands."
    d "Remembered what you promise [p]. Don't go back on your words just because you were healed."
    p "T-.."
    d "Huh?"
    "[p] whole body tremble, his voice cracks up as his tears keep falling down."
    p "T-thank you [d]."
    "[d] was suprised. This is the first time he really saw that gratitue and happy expression from [p]. It was toward him even though he was the one who causes all of it."
    "Has [p]'s mind finally breaking apart?"
    "[p] grasps his trouser."
    d "What do you want now?"
    "[p] hugs his leg tight and rubs his head there."
    p "P-please [d], stay like this for a little longer."
    d "..."
    d "I'm not planning to go anywhere."

    "At the throne room, [p] sits on [d] and pleasure him."
    p "Ahhhh...aaa..."
    d "Hgh!"
    h "And for the finale situation, the North had been in a huge drought. It's devasting there, king [p]. What do you suggest us to do?"
    p "..ahh...haaa..."
    p "....a...S-stop the taxes...a...and...ngh...transfer...water there...uhm..."
    d "Hgh!"
    h "King [p], we already thought of that but the water won't be enough..."
    d "We need more money to spent on parties and decorations [p]."
    p "...A...uhm..."
    "[d] observes [p]."
    p "A...r-raise other places' tax...uhm..."
    d "That won't be enough."
    h "K-king [p]..."
    p "Ahh...r-raise other places' tax, and tax the North like usual...uhm..."
    d "That's my belove king. You heard him."
    h "Y-yes your Majesty!"
    p "Ahh...a..."
    "[p] cums."
    p "A..haa..."
    "[d] careless his cheek and glance at his empty face."
    d "Do you despite me for turning you into this?"
    "[p] touches [d]'s hand."
    p "[d]...[d]..."
    d "..."
    p "[d]...my savior...my salvation...my God..."
    d "You completely lost it huh?"
    p "Please [d], don't ever leave me... I'm nothing, I can't do anything without you..."
    p "I love you. Please, don't ever leave me alone."
    "[p] hugs [d] tightly. [d] hugs him back."
    d "Listen [p]. Even if you are too broken that you shatter into pieces, I will never leave you, got it?"
    p "[d]...my God...I love you..."
    d "I love you too, [p], since the day I met you."
    "[p] cries. He hugs [d] tighter. There was no sound comming from him, but [d] can feel a lot of tears falling into his chest." 
    "[p]'s determined and stubborn side had gone, the only things left were is his weak, submissive and dependent side."
    "[d] wipes his tears, and sit in the same position until [p] stops crying and passes out."
    "[d] careless [p]'s sleeping face and kissed his head."
    p "Uhm..."
    d "You finally belong to me now."

    "End"

    





    

label goodend:
    "[d] touches [p]'s chin and moves it up."
    p "..."
    "[d] kisses [p]"
    p "n!"
    "[d] kisses him harder"
    p "..."
    "[d] stops"
    p "I don't understand you. Why did you do this to me and then ..."
    "[d] hugs him"
    p "What do you want me to do? Hug you back? Push you away?"
    d "Hug me back"
    p "..."
    "Too tired of all the things happening. [p] hugs [d] back. He felt some kind of mana flow through him."
    p "(My wounds...)"
    d "..."
    "[d] takes a deep breath. He looks tired. He had lost a lot of mana and energy"
    p "From the beginning, is it your plan to turn me into a monster? You fucked me, humiliate me, to destroy my ability to fight back then force my mind and body to accept the alteration"
    d "Is it that hard for you to think by yourself instead of asking?"
    p "..."
    p "Why?"
    d "Like I said, you are entertaining. I want to keep you here with me forever, as a pet"
    p "You said if I haven't meet you, I'll be dead sooner or later. How much time I have left in that moment?"
    d "A year, that is if you not continue to push futher away from The Flow"
    p "I'm gonna kill that damn shit, and you too"
    d "You cannot, for now"
    p "So what am I right now? Some kind of a combination of monster, God, and human?"
    d "You are no longer a human"
    p "One day I'll murder all of you, and God too"
    d "God died, a long time ago"
    p "..."
    p "Killed?"
    d "Some of God creation can live forever, but God restained by time"
    "[p] laughs"
    p "Why am I even listening to your bullshit? None of the thing you said make any sense"
    d "It must be hard for your brain to consume things even a 5 year old kid could understand"
    p "..."
    "[p] looks at [d]. It's not a normal one but a shy look. Like he wants something but embrassing to say it, he doesn't want [d] to know but his eyes got caught." 
    "Suprise, 4 eyes look at each other for a few second then [p] looks away"
    p "..."
    "[d] pushed him to the ground and kissed him"
    d "You must have missed my cock. It had been long since this baby entered your ass"
    p "..."
    "[d] holds [p] up, in the spoon position"
    d "I'm not going to serve you forever prince, if you want it, do it yourself. Lucky for you I'm already hard"
    p "..."
    "[p] puts [d]'s dick in and start to shakes"
    "[d] moves up"
    p "No! Ahhh! What are y-"
    "[d] puts [p] on a fallen column and thurst his cock in"
    p "Ahh...[d].. Too deep"
    "[d] smirks"
    d "You like it better right? What do you want me to do [p]?"
    p "Ngh...ahhh...uhm..."
    d "Huh?"
    p "Ahh...[d]..d-deeper, but s-slower...ahhh"
    d "You like it slow? I will go as slow as the speed your brain functions"
    p "Ahhh...[d]...[d]...ahhh"
    d "If you are satisfy, tell me that you love me. So I can continue satisfy you as charity"
    p "Ahhh...ahhhh...[d]"
    d "Uhm huh"
    p "Ahhh... it's good, it so good..."
    p "uhm...ahhhh...[d]"
    d "Say it"
    p "hmmm...ahhh...so good..."
    p "hmm..."
    d "Huh?"
    p "Ahhh...[d]...[d]... I-I.."
    d "Huh?"
    p "I-I love you [d]. I love you...ahh...haaa..."
    p "ahhh...good...You are great...ahh..."
    d "I love you too [p]"
    p "ahhh...hmp...ahhh... [d]"
    # cum
    p "ahh..ahh...[d]"
    "After a while"
    d "We break all record today [p]. Are you still alive?"
    p "Still conscious"
    d "Good"
    "[d] reaches his arm and leg to [p]'s body like he hug a pillow"
    d "Warm"
    p "I'll be your bitch if that's what you want"
    d "Huh?"
    p "I said I'll be you bitch, lover, whatever you call."
    d "..."
    p "Give me some cloth to wear, and decent food. A real place to stay. Stop treating me like an animal."
    d "You recover fast. Yesterday you just told me you are an ani-"
    "[p] turns back and hug [d]"
    p "I'm going to sleep."
    d "Tommorow I'll give them to you."
    p "..."
    p "(It's no used going against him. I'll just make him happy and learn all I can to use this new power. God, The Flow, The Stone, and him, I'll murder all)"
    "[p] holds [d] tighter"
    "[d] stokes his head and kisses on his forehead"
    d "Goodnight [p]."
    p "..."
    "[p] looks at [d]. This is the first time [p] look at his face carefully."
    "Before, it was just a blury figure. He can remember [d]'s eyes, nose, mouth. But he had never look at his entire face or body."
    "Why did he try to figure out how [d] look, [p] doesn't know."
    p "..."
    "Being stared at directly for a long time, [d] looks away. Suprised, [p] also looks away."
    p "(I never thought he can also have a humanly reaction like that.)"
    "[d] turns his eyes to [p] again."
    d "Is there something in my face?"
    p "No..."
    "[p] hugs [d] tighter and closes his eyes."
    p "(The weather's warm today)"
    d "If you are still awake, today is a starry night."
    p "..."
    "[p] looks at the sky of a thousand stars."
    p "It's beautiful."
    d "It is."
    "END"

    

  