####################################################################################################################################################################################### Mind control
label control1:
    "[d] looks at [p]. His eye turns red"
    d "..."
    d "(Not working!)"
    jump sim
    
label control2:
    "[d] looks at [p]. His eye turns red"
    "[p] touch his chest."
    p "..m.."
    p "(What just happens?)"
    d "(I have reached into his mind but the barrier is too strong. Have to break him more)"
    jump sim
    
label control3:
    hide screen day
    hide screen stat
    "[d] looks at [p]. [p] scares. He quickly looks away. [d] chuckles"
    d "Your ego had finally fall into place with your situation huh?"
    p "..."
    "Ego is now an expensive word for [p]. Even his self estem had dropped to the point of no return after days and days of constant abuse and humiliation"
    "Sometimes he wonder if this is all a dream, a general like him, who killed hundreds of monsters, had to kneel and beg for neccessities: food, water, unrine, stool and constantly got disgrace, beaten and fucked by a monster like this"
    "He angry, but now, he doesn't have any courage left to glance at [d] like he used to be. The punishement was too much for him to bare. Physiccally, and mentally."
    p "(If this keeps on, I'll go insane. I should not make him mad)"
    d "Why are you looking while I was talking?"
    p "..."
    "[p] looks at the monster."
    p "...[d]"
    "[d] smirks. His eyes turn red."
    p "..."
    p "(What is this feeling, it's like he penetrating my mind)"
    d "Release him Pitchy!"
    p "..."
    "The vines release [p]"
    d "What are you doing? On your four and crawl here!"
    "[p] feels like his body moves against his will."
    p "Mnh"
    d "(Why I cannot control myself? I tried to stop but my hands and legs crawl to him on its own)"
    "[d] touches his face."
    scene fin_touch
    p "Ngh!"
    d "Good boy. If you were to obedient like that from the start, I would have treat you better."
    p "(My head. It hurts)"
    d "Suck this"
    scene fin_mouthb
    p "MNGH!"
    "[d]'s thumb thrust in [p]'s throat"
    d "I feel pity for you. You were a strong will, egolistic prince. Now, you are nothing more than an animal that about break"
    scene darkforest
    "[d] takes his hand out of [p]'s mouth and moves to his chin."
    p "?"
    "[d] kisses [p]"
    p "!"
    p "...."
    "He pushed [p] to the ground"
    scene deepimpact_head
    "[d] grasps [p]'s legs and start to put his dick in." 
    p "Mgh!"
    p "Please [d], not no-...Agh!"
    d "You don't sound congruent"
    p "Ahhh...Ahhh..."
    "[p] doesn't want it. But he know it'll be better if he lets the monster slams his dick in his ass."
    p "..M...ngh..."
    "[d] enters [p]'s agnus slowly."
    p "...Ngh..."
    p "...You...m..."
    "This is the first time [p] didn't feel any pain when having sex with [d]. There is only pleasure flowing through his veins."
    p "..M...n..."
    p "...Stop it [d].. If you want to violate me. Do like what you always ...arghhh..."
    d "Hmph... You act rather cute today"
    p "...No..Please st-"
    p "...Ngh....m...aah"
    d "You twitch a lot [p]. You like it this way don't you?"
    "Ater [p] gets use to it, [d] slams [p] faster and stronger."
    scene deepimpact_deep
    p "..N...ngh...no..no I don't...ahhh.."
    "[p] cries. It's normal for him to burst his tears while having sex with [d] because it hurts a lot. However, right now, there is no pain. What makes [p] cries is his mind."
    d "Why are you crying? Is it too good?"
    p "..."
    d "You are hard to please prince. When I go rough on you, you cry. When I go gentle and let you enjoy, you cry too. What do you want? Rough or gentle?"
    p "..."
    d "Hey, say something."
    p "...mgh"
    p "P-please [d]. I beg you. St-.. mgh!"
    d "You are so eager today [p]. Want to stay with me eternally here? We can fuck like that all day"
    p "...Mgh...h..N-no!...Stop......m..."
    d "Your hole is getting tighter [p]. Did that idea make you happy?"
    p "N-no... Please [d], let me go. I beg y-"
    scene deepimpact_deepcum
    p "AGH!..."
    d "How rare. We both came at the same time. It must be your cute reaction that makes me came this fast"
    p "Ngh! P-please st-"
    d "Just one time won't be enough to satisfy both of us"
    scene deepimpact_deep
    p "N...mgh!...Take it out...please..."
    d "Saying that while squeezing me eagerly..." 
    d "Even your hole have shaped itself to fit my cock. Do you really plan to live without me?"
    p "...ngh! Ahh..."
    d "Why the silent? Don't forget you position so soon just because I let you have fun."
    p "...[d]...P-please stop..."
    d "Are you giving me an order, egolistic prince?"
    p "N-no. Have you had enough entertainment? You have rippe off all of my pride and self-esteem. I'm not a prince. Before you, I'm just a shameless pet, a bitch."
    p "Is that enough? I'm begging you. Please let me go"
    d "Hmmph...You said you have no pride left. Will you drink my pee then?"
    p "..."
    p "You already win. Don't you have any mercy?"
    d "You still have some left, I see"
    p "Do you want to destroy it too?"
    d "Open your mouth"
    p "..."
    "[p] opens his mouth"
    menu:
        "Peep":
            "[d] peeps in [p]'s mouth"
            p "Ngmm...mhn..."
            d "Remmbered its taste. It is one of your job too prince."
            p "...nhh..."
            "[d] cleans the pee drops on [p]'s mouth"
            d "Is it hot for a human like you?"
            p "..."
            "[d] kisses [p] again"
            p "Ngh"
            d "Rest well"
        "Smirks and go away":
            "[d] smirks and goes away"
    p "AAAA...UH...UhUhUh...Hic...Hic... *Sniff..."
    "[p] cries out loud, then bites his lip. [p] feels like he can no longer control himself. He asked God that if his limit had been reached"
    d "(I was able to penetrate in 80 percent of his mind. What a long process. No mater how strong or priceful a creature is, normally it just took a week for them to completely crushed)"
    d "(This kid is not even that strong compare to some of the monsters here. But his stuborness and ability to control himself is respectable)"
    d "(It was a suprise the first time meeting him too. Unbalance and Chaos. This world doesn't like him. The Flow is trying to push him away)"
    $control3first = False
    jump sim

label control4_ques:
    "[d] touches [p]'s cheek while he were sleeping"
    p "Uhm..."
    d "Walkup"
    p "..."
    d "Hmph"
    "[d] smirks and brutaly slaps [p]. [p] flies to the left, hit a tree and falls to the ground" with vpunch
    p "Ngh!"
    "[d] stomps on his head"
    p "Hph!"
    d "Pretend not to hear me. Are you forget your position just because I go easy on you these days?"
    p "No, master [d]"
    d "No, master [d]. That's right"
    "[d] stomps on [p]'s head again and lift his foot off"
    "[p] licks his foot"
    p "Mgh..."
    d "At least you still know how to flatten me"
    "[p] heard some noises. The mosquito monsters appeared from the bush"
    p "[d]! [d]"
    d "Relax, they will not fuck you, I just invite them here for some businiess"
    "The mosquito attach [p]" with hpunch
    p "AGHHH! AAAAGGGGHHH!"
    p "[D]! [D]!"
    d "Hahaha, is it that hard to control your own urine? I can see some stool too"
    p "[d]...Why? Why are you ...doing this?"
    "[d] stomps on [p]'s stomach"
    p "Mgh!"
    d "Why would you even border to understand me? I just do whatever interesting to me"
    "[p] cries"
    d "Cries again? Had you become meek? Or have you gone insane?"
    "[p] grasp his leg and scrath it"
    p "FUck you! Listen or don't, you treat me the same. Yet, yet I believe and humiliate myself to amuse you"
    "[d] kicks [p]"
    d "So what? What can you do? Crying to mama? Oh wait, do you even have one? How about crying to your papa? Who will kill you if he sees you like this?"
    p "AAAAAHHHHH"
    "[p] gets up from the ground, punches [d]"
    d "Is that suppose to be a punch?"
    "[p] throws another punch. [d] catches it and breaks his arm"
    p "AGGHHHHHHH!"
    p "Haa...haa..."
    d "I have always amaze [p]. Are you really one of your country champion? It's a miracle that you can train yourself to this level. But you have no blessing or talent"
    "[p] escapes [d] and throws him a kick"
    "[d] breaks [p]'s leg"
    p "AAAAGGGGHHHH!"
    "[p] falls to the ground"
    d "It must be normal when you are born. But the more you grow up, the more you train and improve, the more the world turns its back on you. You already notice this right?"
    p "Haaa...haaa...Shu- u-... haaa..."
    "[p] tries to stands up"
    d "You have gone out too futher away from the role The Flow created. This world is pushing you out. Even if it's not me, you will die a painfully death"
    p "Ha..haa... So I have act as you wanted, and now you have become tired of me and want to kill me yourself?"
    d "What do you think?"
    "[d] kicks [p]"
    p "Haaa...ha...ugh...haaa..."
    p "Haa...Give me the stone... I can fix this...I can change... haa..haaa"
    "[d] laughs"
    d "The existents that is able the bend the rules God left, have to be in ultimate harmony with it. Only the creations chosen by The Flow can use The Stone"
    d "Do you know what existent The Stone hate the most? You. The moment you touch The Stone, either it or you will be destroyed."
    p "Am I also the existent you hate the most?"
    "[d] smiles"
    d "What do you think? I am also a creation of God that is born in the day to project The Flow and The First Stone. So that this world will keep on living"
    p "Kill me. You should have done it from the start. What are you even doing? I have to die while my self-esteem plummet to the ground. Is that how much you hate me?"
    "[p] looks like he had had enough. He already given up all hope. He doesn't even have any will left to live. [d] touches [p]'s shoulder"
    d "Look at me"
    p "..."
    "[d]'s eyes turn red. Again, [p] feels like his head was penetrated. [d] thrust his hand into [p]'s head, then his brain"
    p "Ughh...aaa..."
    "The pain were too much that [p] cannot even scream. [d]'s fingers go on deeper and deeper. With each thrust, [p] feels like thousands of needle attach his brain"
    d "Hmp, I think this is the sexual part of the brain"
    p "Mmm...mngh...m..."
    "[p] cock hard on its own and cum. How much [d] want him to suffer before killing him off?"
    "[d] keeps on penetrade deep in the sexual part of the brain. [p] pain was lessen and replace by plessure"
    d "Hand on a bit"
    "All 5 fingers of [d] had penetrate to the deepest part of [p]'s brain. [d] feels a flow of energy comming in. It comes faster and heavier each second."
    p "Ngh!"
    "[p] becomes unconscious"
    d "[p], [p]"
    p "ngh"
    "[d] touches [p]'s face"
    
    "The next morning, [p] wakes up"
    p "Am I still alive? I can't even feel myself"
    "He reaches his arms and legs, but they are heavier than usual, like they had some root connected to the Earth"
    p "Shit! What the fuck is going on?"
    "[p] remembered all the things [d] did to him yesterday"
    p "Since the begining, he tries to weaken my will. And yesterday, yesterday, he goes deep into my mind, I'm unable to stop it. He changed my brain, no, he change my whole body."
    "[p] heard hand claps"
    d "You guess right [p], you had become smarter. A five year old kid could have the same conclusion as you, only faster."
    p "[D]! FUCKER! WHat Have You Done?"
    d "It just seems like we are back to phrase one, should I re-teach you from the beginning?"
    p "Just kill me! What did you turn me into?"
    d "Don't worry, you won't ever die. You have become immortal, just like me."
    p "!"
    d "You are no longer disrubt The Flow of this Earth since you have become a half breed of monster and the Earth itself like me"
    p "No, this can't be happening"
    d "The only drawback is your arms and legs are the Earth, you cannot move for now. But it's a cheap price right? Beside, your 2 slutty holes is till easily accessible"
    p "[D]! YOU BASTARD!"
    "The ground moving faster and faster, [p]'s arms and legs cracks. He consumes the Earth and get his new arms and legs"
    d "Not bad."
    "[p] thurst to [d], [d] call thousands of spikes formed from the ground and shoot at [p]. An explosion, dust flying everywhere"
    d "You have plan to escape from the start huh. Have you become smarter or more aware of your opponent level?"
    "[p] runs. He doesn't know where did he runs to. He just run forward"
    p "([d] didn't able to catch me. It seems like he had become weaker. Is it because of the thing he did to me?)"
    p "Water sounds"
    "He turns and runs to a waterfalls. The demon said to him there is only one river here. The Stone is either top, or down"
    "He looks at himself in the river and kneel down"
    p "That fucker, why did he hate me so much. So disgusting" 
    p "I should have killed myself the moment he captured me. I wanted to live that time. I accepted all the humiliation and let him trambled all over me"
    "[p] doesn't know which word of the monster is true. He can tried to get out of this forest, or find the stone"
    p "Even if I can get out, he will still find me. If he captured me again, I can no longer escape. He will beat me like an animal and fuck me like a whore whenever he likes." 
    p "He will force me to beg and do all the disgraceful things till my mind scatter to pieces."
    "[p] heard a foot step"
    p "Who?"
    n "Mr.Knight? What happen to you?"
    p "You!"
    "[p] grasp [n]'s shoulder"
    p "Where is the stone? Is it upstream or down stream?"
    n "I-It's downstream"
    "[p] looks behind him"
    p "So it's this way"
    n "..."
    p "What if I can't find it?"
    "[p] grasp [n]'s shoulder hard"
    p "Go with me!"
    n "No, I -"
    "[p] carries him and run like flying"
    n "It's there"
    p "I didn't see anything"
    n "In the middle of the river, there's a temple"
    "[p] tries to look, but it just all water"
    p "Guide me, I cannot see a thing"
    n "Right now! Go to the middle of the river"
    "[p] form the ground into a bridge"
    n "Its sir [d]'s power..."
    p "!"
    p "I can see it now. We have to hurry!"
    "[p] can sense that [d] is really close"
    p "Where Is The Stone?"
    n "Ah! Up there, on the status hands"
    p "!"
    n "!"
    d "What do we have here? A half-ass monster and a demon"
    "[d] steps closer to [p] and [n], his footsteps become louder"
    "[p] jumps to the statue hands"
    d "Running away?"
    "A big hand slaps [p] to the ground"
    p "Mgh!"
    "[p] forms the ground to a giant hand and attacks [d]. [d] negates it."
    d "!"
    "[p] jumps to the status' hands. [d] destroy the status, [p] falls to the ground."
    p "Ugh!"
    "The Stone falls the [d]'s place"
    p "..."
    n "Ahh!"
    "A column falls onto [n]. With a swift moment, [p] pushes him away. Both fall to the ground"
    p "Kuh"
    "[p] stands on 1 knee. [d] kicks the stone to [p]"
    p "..."
    d "It just a rock I put there 300 years ago"
    "[p] touches the stone and crush it"
    p "Is The Stone just a lie God make up?"
    d "No. You are closer to it than you think"
    p "..."
    d "How about we make a bet?"
    p "What is it?"
    d "I show you where The Stone is. If you can get it or use it, I'll not touch you anymore. If not, you know what comes next"
    p "Where is the stone?"
    "[d] points toward [n]"
    p "Impossible. What kind of joke is this?"
    d "He should have died a long time ago. The Stone save him, and I put inside his body as its will. Hard to believe huh?"
    "[d] eyes turn red. [p] can see the stone inside of [n]"
    p "..."
    "[p] penetrates his hand into [n]'s chest"
    n "Ahhh...Sir.Knight, p-please..."
    p "Ahhh...Arghhh..."
    d "The energy born from yours and the stone contacting each other will kill [n] first"
    p "Ahhhh...Arghh...."
    n "S-sir Kni- pleas-..."
    "[p] had pass the outter barrier"
    n "Ahh...Ughhh...ahhh..."
    p "Ahhhh...Arghhh....."
    p "[n]! If you don't want to die. Use its power. Either kill me, or [d], or both of us. This is a fair game. I'm not gonna hold back"
    n "N-no. Please stop. I won't. I won't .... ahhhhh..."
    "[p] almost the inner barrier"
    p "Arghhh...Arghhh..."
    p "(It's your false to not participate in this life and death game. Sorry)"
    "[p] remmembered the time the demon help him to get water, and his worried expression when he turns into a monster." 
    "The demon not once was afraid of him. He offers help and got his life taken away by the one he helped in return"
    "The very first reason [p] wants to become strong was to lesser his father burdern. The second reason was to make his country stronger and everyone lifes better. The third reason was to protect his dad, brother, and people he cares"
    "He doesn't know when or why things turn out this way. His country feared him, his father hated him and his brother pity him. Since when did he drop his humility and kill his opponents mercilessly without reasons to archive a goal"
    "[p] cries. He puts his hand out of Nine's chest"
    n "Ahhh...haa...ahhh..."
    n "ahh..S-sir. Kni-.."
    "[p] punches [n]"
    n "Mgh!"
    p "Go away! If I ever see your face again, I'll kill you! I'll kill you for sure!"
    n "...."
    "[n] runs away"
    "[d] comes closer as [p] crawing and crying on the ground"
    p "..."
    p "I lost the bet. Will you fuck me now? Make me your bitch? Force me to suck your cock? Drink you pee? Or it's time for a new kind of torment?"
    d "What do you think?"
    p "Stop that already. Didn't you said I'm a birdbrain? How can I know what a genius like you think?"




label badend:
    d "Don't start to flatten me already. It won't lessen your punishment"
    "[p] smirks"
    p "Why should I flatten you? You smart enough to share your power to your most vegenful victim. Why is it? Don't tell me that you ..."
    p "I feel nasseus in my mouth right now when thinking about it. Am I suppose to give you a piece of my heart as a charity?"
    d "..."
    p "Will the power you share to me ever comeback? It'll be a funny story if you lost it forever." 
    p "Oh wait, I can sense it. It won't be back. I can even know when you are weakest." 
    d "..."
    p "Should I tell this news to every creature in this planet. Maybe one of them can finish you off"
    p "Why don't you say anything, master Smarty?"
    "[d] laughs"
    d "You learn fast. I'm kind of impressed. But it seems like after you learn something news, you forgot the old one"
    d "What I give, I can take back. And it won't be as pleasant as when I give." 
    d "Oh, when that happens, you won't be able to return to human again, but a half-God half-monster trash that can't move and can't die"
    p "..."
    "[d] kicks [p] to the ground"
    p "Mgh!"
    d "What should I do with you now? Ah, how about reunite with your family?"
    d "Oh wait, I want you to meet a few new friends before that"
    p "!"
    p "No! NO! PLEASE DON'T! I'M SOR-.. AAAAGGGGGHHHHHHHHH....."
    "[ri] castle, in a meeting with 50 dukes, duches, followers and generals"
    h "[k], there's a person from Eyon castle said he knows prince [p] where about. He also want to give you a present as a peace deal"
    ren "Let him in"
    k "..."
    d "Dear [k], lord of the Holy Land, we heard that prince [p] is in the Dark Forest"
    k "Dark Forest..."
    ren "We haven't send troops there. Call the military generals"
    d "That won't be neccessary"
    ren "?"
    k "!"
    d "Because he is right here!"
    "[d] shows his true form and gets the table cloth out of the way"
    p "Mgh! Ngh!"
    "[p] was lying under the table, suffering. His ear, mouth, ass, and pee hole constantly penetrated by some kind of insect monster"
    "[d] grasp his hair, and throw it to the throne."
    ren "Borther!"
    h "Prince [p]!"
    p "!"
    k "[ren]! Stop!"
    d "That's right prince [ren], you father was right. These creature like to host on warm body. Once it move to you, it can't be taken out"
    d "They will suck your energy while find their way to a warm place like asshole and shoot their poison needle to that place"
    d "Once the process is done. They'll send their eggs in. When the host die, the Spazies baby will destroy the barrier and jump out like flies"
    ren "No! Brother!"
    d "Don't worry, unlike you, your brother won't die... Because I had turn him into a monster"
    ren "You are lying!"
    k "Get out [ren]!"
    d "Oh no. Don't chase him out. There are more monsters outside"
    k "..."
    k "What do you want us to do? Creature of the Dark Forest never went outside. If it is because of [p], it is his problems. He is not a human or even a citizen here"
    p "..."
    d "Did you hear that [p]? Your dad chases you out"
    p "Mgh! Ngh!.. Mmm..."
    d "Don't tell me you are too into sex that this event didn't mean anything to you"
    k "Please bring him out, together with all your monsters"
    d "What do I do? I already promise him to let him sit on the throne"
    h "Prince [p] make a deal with that monster?"
    h "I don't want to get involved"
    "[d] grasp [p]'s hair and throw him to the throne"
    d "There, finally, after all the troubles, you are there. Tell us your feeling [p]. Who do you want to thnks first?"
    p "..Mmgh...Nmm...."
    d "Huh? Is there anything wrong prince?"
    "The insect monster let go of his mouth"
    p "[d], [d], I have to ..."
    d "Oh"
    "The insect penetrate his mouth again. The other insects let go of his pee and ass hole"
    p "Nhhm"
    "The insects send electric"
    p "MMM...! HHH...! NNN.."
    p "MMMM"
    d "Oh wow, king [p] cannot control himself. He piss and poop on the throne, what should I do?"
    d "Shouldn't you learn the mess youself?"
    "[d] grasp his hair and throw him to the ground then sit on the throne"
    d "Clean it with your mouth"
    "[p] licks and eat it."
    "[d] touches [p]'s face."
    d "Hey you!"
    h "Y-Yes sir!"
    d "Chain this dog and walk him around the city!"
    h "Yes sir!"
    "[p] quietly let the servant chain him. He crawl on four, like a dog. [d] whispers."
    d "Do you want your family to escort you or do you want me to chase them out?"
    p "Please chase them out, far far away from here... to other country."
    d "You heard that [k], gather everyone, told them you were dethrone. Now, this country is mine."
    k "No, you can't..."
    d "If you do it well, no one will suffer greatly. Else, I'll told my friends to do whatever they want."
    k "I-I uderstand."
    "The king goes away. He told the mage to prepare the magical sky screen for the announcement."
    p "..."
    d "Now your turn [p], let see how happy the citizen is when their prince is still alive after the country fallen."
    "[p] shivers."
    d "Told the citizen I gave them permission to do whatever they want aside from killing him."
    h "Yes sir!"
    "The servant holds the lease forward."
    h "Move fast!"
    "[p] mind become empty, he didn't move an inch."
    "The servant whip him!" with hpunch
    p "Ugh!"
    h "I said move! Did you still think you are really a prince."
    p "..."
    "5 hours later."
    h "Prince [p] had come back"!
    d "..."
    "The servant had to hold [p] and pushed him in. [p] was in a critical condition. He was beaten and sratched from head to toe. Blood and sperm everywhere. His hands and legs was chopped off, his tongue is not there anymore. His eyes were taken away using a clean and neat technique"
    h "S-sir, you told me not to interfer"
    d "You did great!"
    "[d] puts his finger into [p]'s ass"
    d "At least they keep the most valuable part of your body huh?"
    p "M...m u-..."
    d "I don't get what you are saying. If you can't speak, write it down."
    d "Oh, I forgot. You can't. Hahaha."
    p "Ua,...u-..."
    d "Someone put something in his mouth. It hurts my ears. If they cut the tongue, cut all the way, so there's no sound coming from him."
    ## sock in mouth
    p "Ugh..N!"
    d "Throw him into a dog cage! Find a small one that fits his current body and makes he unable to move even an inch!"
    "At night, [p] cries. He knows that his hands and legs can regenerate if he did right. But what about his eyes and tongue."
    "He tries, but he cannot uses the power."
    p "Hmp...ahh...mmm..."
    d "You look like a bitch in heat."
    "This is the second time [d] comes to [p] at night, beside the first time they meet."
    "He throws water from a basket at [p]."
    p "Au..u...a.."
    d "That's to clean you up first. You wouldn't want to have dissease right?"
    p "...m..."
    "[d] opens the cage and pull [p]'s hair, grags him out of the cage."
    p "Ugh! Hmp..."
    "[p] can hear a sound of cloth smashing each other. The next thing he knows is [d] penetrates him."
    p "Uh!..Ugh..."
    d "What a pervert. You can even feel it in this situation."
    "[p] cries."
    d "You cried a lot today [p]. Had you become meek now?"
    p "Umm...Ngh..."
    "Both of them cum."
    p "Hm..n...ugh..."
    "[d] wipes [p]'s tears."
    d "Are you hungry?"
    "[p] nods."
    d "Thirsty?"
    "[p] nods."
    d "I bring your meal here."
    "[d] pulls the sock out, carries his head and gives him water."
    p "Ugh...uhn..."
    "[d] spoons feed [p]."
    p "...a..u.."
    d "What's wrong? Oh, Seems like your jaw got dislocate. It'll be painful to chew huh?"
    "[p] nods. [d] chews the food and feeds [p] by mouth."
    p "Hmm...hmmm..."
    "[d] kisses [p]."
    p "Umh! Uhm!"
    "The kiss becomes more passionate."
    p "Uhm...Ughm!"
    "[d] stops."
    d "Let put you back to the cage."
    p "Ua..u..! Aa.."
    "[d] puts [p] back to the cage and locks it. He puts in some water and food in the dog feeder."
    p "Ua..a...u..."
    d "What's wrong?"
    "[p] shakes his head."
    d "Ah, it'll be painfull for you to eat and drink by yourself since your jaw was dislocate."
    d "I'll comeback tommorow and feed you."
    p "Aa...! Au....u..."
    "[d] continues to lock [p] up in that cage for 3 months. Aside from him, no one was allowed to get in."
    "Unable to move, no sound to hear aside from [d] voices and footsteps drives [p] insane to the point being fucked by [d] senselessly and being feed food and water are what he waits for everyday."
    "[p] hears a noise. He knows that [d] is walking in. The door opened for a few minutes then closed."
    "He was waiting for [d] to step close and get him out of the cage, but everything was silent."
    p "Ua..u.."
    "There was no response. [p] waits and waits but there is still no sound. No one was here. Was he hallucinating?"
    p "..."
    "He doesn't know how many days had passed since [d] not coming. Despite the pain, he eats and drinks in the dog feeder to survive. The only desire he was unable to fulfill is sex."
    "[p] rubs his cock against the floor, but since he cannot move an inch, it just make the desire stronger and him to suffer more."
    "Several days later, he heard footsteps and the sound of the opened door."
    p "A...u..."
    "[d] pulls him out of the dog cage and kisses him."
    p "Uaa...nhm..."
    "He kisses [d] back."
    d "You look more eager than usual. Do you missed me?"
    p "A..ua...a.."
    d "What does that mean?"
    p "..."
    "[p] nods his head."
    d "You really miss me? How cute!"
    "[d] fucks [p]."
    p "M...A...Ua...h..."
    d "You feel it more today huh?"
    p "A....aua...."
    "[p] cum."
    "[d] presses his mouth into his cock."
    p "H...m..."
    d "You didn't even have legs to move youself up and down. Pressing you head in and out like this makes you look like a sex toy huh?"
    p "M...Ngh..."
    "[d] cums. [p] drinks it."
    p  "M...n..."
    d "After today, it'll took a week until I can get here again."
    p "U..a..."
    d "There was a lot of interesting things to do now I'm in charge of this castle."
    p "A...u..."
    "[p] presses his head into [d]'s chest. [d] careless his head."
    d "Do you want to come with me? I'll let you lie on the throne. I'll sit on your face, while everyone can see your cock and asshole."
    p "U...a...uaa..."
    d "What?"
    "[p] nods."
    d "Hahaha, are you that desparate? You make me want to cry now."
    "[p] presses his face in [d]'s chest harder and kisses it. [d] notices and touches his face."
    d "How about this prince? I will return your body to normal, make you king like you always wanted."
    d "In return, be docile and act cute. Listen and follow my every word, as if I'm your God."
    p "A...a..."
    "[p] nods."
    "[d] stands up, creates an energy sphere and pushes it to [p]. His whole body glow up and returns to normal."
    p "A..."
    "He looks around with his eyes, holds his throat, touches his arms and legs."
    p "A...haha..."
    "[p] cries. He covers his face with his 2 hands."
    d "Remembered what you promise [p]. Don't go back to your words just because you were healed."
    p "T-.."
    d "Huh?"
    "[p] whole body tremble, his voice cracks up as his tears keep falling down."
    p "T-thank you [d]."
    "[d] was suprised. This is the first time he really saw that gratitue and happy expression from [p]. It was toward him even though he was the one who causes all of it."
    "Has [p]'s mind finally breaking apart?"
    "[p] grasps his trouser."
    d "What do you want now?"
    "[p] hugs his leg tight and rush his head there."
    p "P-please [d], stay like this for a little longer."
    d "..."
    d "I'm not planning to go anywhere."

    "At the throne room, [p] sits on [d] and pleasure him."
    p "Ahhhh...aaa..."
    d "Hgh!"
    h "And for the finale situation, the North had been in a huge drought. It's devasting there, king [p]. What do you suggest us to do?"
    p "..ahh...haaa..."
    p "....a...S-stop the taxes...a...and...ngh...transfer...water there...uhm..."
    d "Hgh!"
    h "King [p], we already thought of that but the water won't be enough..."
    d "We need more money to spent on parties and decorations [p]."
    p "...A...uhm..."
    "[d] observes [p]."
    p "A...r-raise other places' tax...uhm..."
    d "That won't be enough."
    h "K-king [p]..."
    p "Ahh...r-raise other places' tax, and tax the North like usual...uhm..."
    d "That's my belove king. You heard him."
    h "Y-yes your Majesty!"
    p "Ahh...a..."
    "[p] cums."
    p "A..haa..."
    "[d] careless his cheek and glance at his empty face."
    d "Do you despite me for turning you into this?"
    "[p] touches [d]'s hand."
    p "[d]...[d]..."
    d "..."
    p "[d]...my savior...my God..."
    d "You completely lost it huh?"
    p "Please [d], don't ever leave me... I'm nothing, I can't do anything without you..."
    p "I love you. Please don't ever leave me alone."
    "[p] hugs [d] tightly. [d] hugs him back."
    d "Listen [p]. Even if you are too broken that you shatter into pieces, I will never leave you, got it?"
    p "[d]...my God...I love you..."
    d "I love you too, since the day I met you."
    "[p] cries. He hugs [d] tighter. There was no sound comming from him, but [d] can feel a lot of tears falling to his chest." 
    "[p]'s determined and stubborn side had gone, the only things left were is his weak, submissive and dependent side."
    "[d] wipes his tears, and sit in the same position until [p] stops crying and passes out."
    "[d] careless [p]'s sleeping face and kissed his head."
    d "You finally belong to me now."

    "End"

    





    

label goodend:
    "[d] touches [p]'s chin and moves it up."
    p "..."
    "[d] kisses [p]"
    p "n!"
    "[d] kisses him harder"
    p "..."
    "[d] stops"
    p "I don't understand you. Why did you do this to me and then ..."
    "[d] hugs him"
    p "What do you want me to do? Hug you back? Push you away?"
    d "Hug me back"
    p "..."
    "Too tired of all the things happening. [p] hugs [d] back. He felt some kind of mana flow through him."
    p "(My wounds...)"
    d "..."
    "[d] takes a deep breath. He looks tired. He had lost a lot of mana and energy"
    p "From the beginning, is it your plan to turn me into a monster? You fucked me, humiliate me, to destroy my ability to fight back then force my mind and body to accept the alteration"
    d "Is it that hard for you to think by yourself instead of asking?"
    p "..."
    p "Why?"
    d "Like I said, you are entertaining. I want to keep you here with me forever, as a pet"
    p "You said if I haven't meet you, I'll be dead sooner or later. How much time I have left in that moment?"
    d "A year, that is if you not continue to push futher away from The Flow"
    p "I'm gonna kill that damn shit, and you too"
    d "You cannot, for now"
    p "So what am I right now? Some kind of a combination of monster, God, and human?"
    d "You are no longer a human"
    p "One day I'll murder all of you, and God too"
    d "God died, a long time ago"
    p "..."
    p "Killed?"
    d "Some of God creation can live forever, but God restained by time"
    "[p] laughs"
    p "Why am I even listening to your bullshit? None of the thing you said make any sense"
    d "It must be hard for your brain to consume things even a 5 year old kid could understand"
    p "..."
    "[p] looks at [d]. It's not a normal one but a shy look. Like he wants something but embrassing to say it, he doesn't want [d] to know but his eyes got caught." 
    "Suprise, 4 eyes look at each other for a few second then [p] looks away"
    p "..."
    "[d] pushed him to the ground and kissed him"
    d "You must have missed my cock. It had been long since this baby entered your ass"
    p "..."
    "[d] holds [p] up, in the spoon position"
    d "I'm not going to serve you forever prince, if you want it, do it yourself. Lucky for you I'm already hard"
    p "..."
    "[p] puts [d]'s dick in and start to shakes"
    "[d] moves up"
    p "No! Ahhh! What are y-"
    "[d] puts [p] on a fallen column and thurst his cock in"
    p "Ahh...[d].. Too deep"
    "[d] smirks"
    d "You like it better right? What do you want me to do [p]?"
    p "Ngh...ahhh...uhm..."
    d "Huh?"
    p "Ahh...[d]..d-deeper, but s-slower...ahhh"
    d "You like it slow? I will go as slow as the speed your brain functions"
    p "Ahhh...[d]...[d]...ahhh"
    d "If you are satisfy, tell me that you love me. So I can continue satisfy you as charity"
    p "Ahhh...ahhhh...[d]"
    d "Uhm huh"
    p "Ahhh... it's good, it so good..."
    p "uhm...ahhhh...[d]"
    d "Say it"
    p "hmmm...ahhh...so good..."
    p "hmm..."
    d "Huh?"
    p "Ahhh...[d]...[d]... I-I.."
    d "Huh?"
    p "I-I love you [d]. I love you...ahh...haaa..."
    p "ahhh...good...You are great...ahh..."
    d "I love you too [p]"
    p "ahhh...hmp...ahhh... [d]"
    # cum
    p "ahh..ahh...[d]"
    "After a while"
    d "We break all record today [p]. Are you still alive?"
    p "Still conscious"
    d "Good"
    "[d] reaches his arm and leg to [p]'s body like he hug a pillow"
    d "Warm"
    p "I'll be your bitch if that's what you want"
    d "Huh?"
    p "I said I'll be you bitch"
    d "Then?"
    p "Give me some cloth to wear, and decent food. A real place to stay. It's cold sleeping in the middle of a forest when it's raining. What am I? An animal?"
    d "You recover fast. Yesterday you just told me you are an ani-"
    "[p] turns back and hug [p]"
    p "Shut up. I'm sleepy"
    d "Tommorow I'll show you, the things you want"
    p "..."
    p "(It's no used going against him. I'll just make him happy and learn all I can to use this new power. God, The Flow, The Stone, and him, I'll murder all)"
    "[p] holds [d] tighter"
    "[d] stokes his head and kisses on his forehead"
    d "Goodnight [p]"
    p "..."
    p "(The weather's warm today)"
    d "If you are still awake, today is a starry night"
    p "..."
    "[p] looks at the sky of a thousand stars"
    p "It's beautiful"
    d "It is"
    "END"

    

  