######################################################################################################################################################### END
label end:
    hide screen stat
    hide screen day
    $n = "Nine"
    scene darkforest    
    p "I have no time. Where is the river? Shit!"
    "After hours of walking, [p] finally found the river." 
    p "It’s here. I found it."
    "[p] go to the North." 
    p "Is this really the right way? What if it's the opposite? Dammit there's no time to hesitage."
    "He sees Nine."
    p "..."
    "[p] walks away"
    n "..."
    n "[p]"
    p "..."
    n "Are you still looking for the stone?"
    p "..."
    n "I'll show you the way."
    p "..."
    p "Why?"
    n "Because you want it."
    p "..."
    p "(What wrong with this demon?)"
    "[p] doesn't understand why is the demon so nice to him. Prehaps, he this way to everyone. \nThere is something about him remind [p] of his brother."
    "They pass a green field fill with white growing birds. [p] had never see this race before. They are not disrupt by [p] and Nine present."
    "[p] suddenly feel all his pain are gone."
    p "How on Earth?"
    n "It’s the birds. They heal you."
    p "There is such a creature like this in the world?"
    n "I think there are plenty of mysterious things in this world we haven’t know."
    p "I’m amaze that they can continue flying freely like this. No monsters in this forest even think of capturing them. \nIf there are creatures like this in human land, they are already in cages, serving the armies"
    n "For us here, they are scared. Monsters can kill each other everyday, but they will never harm what the birds."
    p "..."
    n "When you got what you want and get out of here, will you come back with armies to capture them?"
    p "...If monsters from the Dark forest and Human are at war, I’ll. If I cannot catch them, I’ll kill all of them. They are too dangerous to be alive."
    n "..."
    "Just in a split of second, [p] can see the sadness in Nine’s face. \nFor a moment, [p] thought this demon is even more human than him..."
    "...Is it really true that monsters and demons are cold blood like what he was taught?"
    "Finally, they arrive at the temple."
    n "Let us depart here."
    "[p] holds Nine’s hand."
    p "Wait!"
    n "..."
    p "..."
    p "Stay with me."
    n "..."
    p "It will be safer if you stay near me. [d] might knows you help me. Let me protect you till I get the stone."
    n "I-..."
    d "You are right [p]. You seem to know me well. Prehaps it because we are \"so close\" to each other." ##(he means sex)
    p "!"
    d "[p]!Just because I go easy on you today, you left me and date this child?"
    "[p] drags Nine into the temple"
    d "You can run but you cannot escape me "
    p "Nine, do you know where the stone is?"
    n "In the back of this temple!"
    p "Tsk! Why put it that far"
    "The ground shaking by [d]’s power"
    p "(This is the first time I saw this monster's true power. It's Earth Manipulation)"
    "Nine falls. A thrusting pillars of rocks shoots at him. [p] gets him out and got hit" 
    p "Arg!"
    d "What a surprise! U can actually guard for some one."
    "[p] takes Nine hand and run." 
    n "..."
    "They arrive at the back of the temple. \nAs glorious as the Temple was, its biggest room contained almost no furniture at all. \n[p] can only see pillars after pillars"
    p "Where is the stone?"
    "Nine points at the stone fountain"
    p "(is it inside?)" 
    "[p] jumps in. \nThe room is too dark. [p] can’t see anything. \nHe uses his hands to search."
    p "Help me Nine!"
    "[p] hear no response. "
    p "Nine! Nine!"
    "Suddenly, a pillar of rocks coming at his way, [p] falls in the water" 
    p "m..."
    "[p] gets up. A strong hand pulls his head and slam it in the water"
    p "mmm..."
    "[p] struggles. He is out of oxygen."
    "[d] pulls [p]'s hair back. [p] tries to breath" 
    p "ahhhh...haaaa"
    "His head was slam into the water again." 
    p "m"
    "[d] pulls his pant out. [p] kicks it rapidly"
    "Out of oxygen, [p] tries to get out. A hard, big and hot thing thrust in his asshole"
    p "ahhhh….aaaaa...aahhhh"
    p "S-stop!"
    p "ahhh! Stop it [d]."
    d "..."
    p "[d]"
    d "What a surprise! U can recognise me just by the shape of my cock!"
    p "Crazy ba-..."
    p "arghhhh...ahhhhh...aaaaaaa"
    p "m..."
    p "W-where is Ni-….. aaaaa"
    d "You made me mad [p]. Run away with a demon. Just when I got soft with you."
    p "Ahhhh….ahhhh..."
    p "S-shit…."
    "This is the first time [d] use his full strength to fill [p] ass"
    "[p] cannot stand the feeling. His mind become empty. He cannot think of anything beside feel the pressure and moan"
    p "ahhhh…..ahhhh….haaaaa"
    "[d] cums in [p]’s ass." 
    p "haaaa...haaaa...m"
    p "ahhhhh aaaaaaaa..aaaaa"
    "[d] continue"
    p "Stop it [d]. It hurts too much!"
    d "Shut up [p]!"
    p "ahhhhh...ahhhhh"
    "[p] don’t rememberhow many times [d] cum inside him, but his muscle are numb." 
    "Finally, [d] release [p]"
    p "haa..haaa"
    p "Where i-"
    "[d] slap [p]’s face. [p] falls to the pond."
    p "..h..."
    "[d] smile"
    n "Stop it!"
    d "Not you too?"
    "[d] create a hand and carry Nine to his place"
    d "Never I thought one day can u speak out and look at other with that eyes"
    d "Seem like you two are perfectly fit for each other"
    p "Let him go!"
    "[d] kicks [p]."
    p "Argh!"
    "The hand tighten its grasp."
    n "urgh!"
    p "Let him go u bastard!"
    "[p] used his bare hand to strike Dietrich with a powerful blow. Dietrich steps back. Blood comes out of his veins"
    d "Ho, that is the strongest blow you ever give me. I don’t understand. \nHow can u become stronger after being fucked, caged, humiliate and beaten everyday?"
    p "Bastard!"
    "[p] concentrate his energy and create a barrier."
    d "Are u stupid? What can this-.."
    "A bright light appeared. Too bright for anyone to see.\n While the giant hand loosen his grasp, Nine falls to the pond. [p] drags Nine out and runs."
    "Nine falls. "
    p "U alright? We have to hurry!"
    "[p] sees a stone fallen from Nine hand. Just one look and he knows it is the First Stone."
    "All things in this Earth had energy, vibrating as different frequency. \nThis stone doesn’t have it. It can be touch, yet it is non-exist by normal mean. \n[p] holds the stones"
    d "Hahaha, finally, I have it. You are dead with me [d]. I’ll crush you to thousands pieces. [p] uses his power to take control of the stone." 
    "Nothing happen."
    p "How? It doesn’t make any sense." 
    p "..."
    "[p] looks at Nine."
    p "I have search everywhere but can’t find the stone while you just fall to the pond for a few seconds. \nHow can it be located that quickly?"
    n "I-.."
    p "...You are not a complete living being. There’s a part of you that doesn’t have any energy. Who are you?"
    "[p] hear the ground moving. [d] is coming and he is really angry."
    "[p] touches Nine" 
    p "Tell me, how can I use the stone?"
    n "I-I don’t know."
    p "(Base on the legend, it must be a full stone. \nOnly when parts of the stone united, I can use its power)"
    if show == True:
        jump end2
    else:
        jump end1
label end1:
    hide screen stat
    hide screen day
    "[p] strangles Nine’s neck. "
    n "m"
    p "Only when you die, I can have the full stone. \nIs that the reason you don’t want to go with me to the temple? \nU were afraid I’ll kill you."
    p "But then why you show it to me"
    n "m"
    p "..." 
    p "You thought I can use the not completed stone aren’t you"
    n "..."
    n "n.."
    p "....Too bad I can only use it if you die"
    "[p] strangles Nine’s neck harder."
    n "h….h.."
    "What a weak demon Nine is.\nHe already out of breath. \nPut in some more strength and [p] will have the stone."
    "[p] strangles Nine harder. Nine tears fall out."
    p "..."
    p "Fuck!"
    "[p] releases Nine"
    n "*cough *cough"
    p "Shit!"
    "[p] throws the stone at Nine"
    p "Take this useless stone with you! Don’tever come near me again"
    p "..."
    p "... and don’t help everyone you meet if you treasure your life."
    n "..."
    "Nine runs away."
    p "Shit!..."
    p "..."
    p "Sorry..."
    p "...And thank you"
    n "..."
    "Nine looks back at [p] and continue to run forward."
    
    d "Where is that little demon?"
    p "I tried to kill him, but he ran away!"
    d "Ho, you 2 just seem like loving birds a while ago. What happened?"
    p "Don’t pretend like you don’t know. You are the oldest creature in this forest."
    d "Ha, whatever. You really piss me off this time [p]. I just good to you for a moment and you stab me on the back."
    d "Pets must be train properly everyday, so that they know their place."
    p "..."
    p "I'm not a pet."
    d "I see some change in you [p]. Not as cocky as you used to be. Perhaps it thanks to my teaching method."
    p "Bastard!" 
    "[p]rushes to him"
    d "You are not so bright aren't you? I guess that what happen when human eat sperm everday. Pitchy!"
    "From the ground, Pitchy shoots up. It wrap him and it's vine moving around [p]'s body."
    p "...m...n.."
    "The vine thrust his ass."
    p "...h...ngh...aahhhhhhh...ahhh"
    d "Nice face! You look so lewd [p]."
    p "...m...F-fuck you...!"
    d "As stubborn as ever. I see. Too bad, it never works for me."
    p "..."
    d "Bad kid should be punish harshly so that they never repeat the same mistake."
    d "Pitchy, release your children!"
    "Some creature look like leeches come out from the vines. They climb on [p]'s entire body, go into [p]'s pee hole and ass hole, bite him, suck his energy and give him arphodisac in return"
    p "...aaaaaaaa....hurt...hurt so much...they bite...inside..inside...argh..."
    p "Noooo....ngh..aaaaaa....ahhhhh..."
    d "Seems like you are having fun."
    p "ngh...n-no...I don't...Please..Help me [d]...please help me...tell them to stop"
    d "Hmph...What should I do with you?"
    p "...aahhhh....ahhhhh...Please [d]...Help me...Have mercy..."
    d "I don't know about that. The last time I took pity on you, you run away with someone else, injure my chest and curse me."
    p "....ngh...arghhhh....ahhh...no...[d]...please...I-I wont..do that..again...ahhhh..."
    d "How can I trust you?"
    p "...m...ngh...m...ahhhh..."
    "[p] cannot talk anymore. His entire body fills with pain and pleasure."
    d "You always say \"No no\", but you actually love it don't you?"
    "[d] thrust his cock in [p]'s ass. It touches the leeches there, makes they bite [p] harder and suck more of his energy."
    p "...ahhhh...ahhhhh...aaaaaaaaa...."
    d "Tell me [p], do you want me thrust in harder or stop."
    p "...m...*sob *sob....ngah...h..ahhh....ahhhhha...haaa...no..stop..I can't...take it..."
    d "So you want to stop?"
    p "n...h..."
    p "ngh...n-no...don't.."
    d "I'm confuse [p]. What do you want?"
    p "...ngh...h....ahhh..."
    p "..n..ngh..I-I don't...know..argh.."
    d "Is it really that hard for human to understand themselves? I can tell just by looking what you really want."
    p "...m..ngh...*sob...it hurts [d]. It hurts..."
    p "...n...aaahh..."
    "[d] pulls his dick out."
    p "..n..No..Dont...the leeches...ahhh"
    d "What did you just said? I can't hear a thing"
    p "...n...h...p-please [d], I beg you. Please fill me. Pound me harder."
    d "If you want it, do it yourself."
    p "..ngh...m..."
    "[p] sits on [d]'s cock and rotate his hip."
    p "haaaa..haaa...ahh...nnn..ngh..."
    d "Aren't you eager today?"
    p "..n..m...h-hot...hurt...ngh...my body...I can't...mm" ##cum
    p "..aahh..ahh..haaa..."
    p "..m..n.."
    "[p] faint from pleasure"
    "[d] smile."
    d "Tell your kids to return Pitchy."
    "The leeches retreat from [p]'s body."
    "[d] touches [p]'s face."
    p "..ngh...m.."
    d "He seems to have a good dream."
    d "..."
    d "Don't you think he cute Pitchy?"
    scene black with dissolve
    "END"
    call screen main_menu()

label end2:
   

    hide screen stat
    hide screen day
    p "It must be a full stone. Only when parts of the stone united, I can use its power"
    p "..." 
    "[p] give Nine the stone"
    p "Run away Nine, I’ll deal with that bastard"
    n "But..."
    p "Go!"
    "[p] rushes to Dietrich’s place."
    d "Ha, [p]. You really piss me off this time. \nBe prepare to beg me like a dog and got your holes rip apart. \nA pet must be train properly everyday, so that they never forget their place."
    p "..."
    d "Hmmph, I saw some changes in you. Not as cocky as you used to be. Perhaps it thanks to my teaching method."
    p "Bastard" 
    "[p] rushes to him"
    d "Idiots never learn. Pitchy!"
    "From the ground, Pitchy shoot up. It catches [p]'s legs. [p] falls to the ground"
    n "Stop!"
    d "Ho!"
    p "I told you to get out!"
    n "\"It must be a full stone. Only when parts of the stone united, I can use its power\" that's what u said"
    p "!"
    p "(That’s right! If Nine is holding the stone. It is already united. Nine can use it power.)"
    d "Stop."
    n "?" 
    p "?"
    d "Kids these days, always play with dangerous toy without understand its true function."
    d "Give me the stone, and I’ll let both of u go"
    p "What if we don’t?"
    d "Both of u will be death before 2 parts of the stone merge"
    p "..."
    "Nine throws it to [d]"
    p "!"
    p "What are you doing!?"
    d "Wise choice!"
    d "[p]"
    "[p] clenches his teeth and glance at [d]. Prepare to fight."
    d "It had been such a long time I have so much fun. \nYou are the most interesting plaything I ever had. \nI hope your body can remember me for the rest of ur life"
    p "Fuck you!"
    d "Human never change. I thought you have learn your place."
    "[d] goes away."
    p "..That bastard really keep his word.."
    p "Still, what u are doing just now..."
    n "...[d] understand the stone better than anyone else..."
    p "..."
    n "He was the one who save my life by give me some part of the stone"
    p "!"
    n "..."
    n "..."
    p "Go with me Nine! Get out of this forest. You are not belong here."
    n "So is the human world"
    p "How about I come with you to the Demon world?"
    "Nine looks at [p]."
    n "You are a nice person"
    "[p] laugh"
    p "You are the first person ever say that to me. And probably the last"
    n "..."
    p "Let’s go. To the Demon World."
    "Nine stands still." 
    n "Go back [p]. To the human world."
    p "Why?"
    n "..."
    n "If I wanted to leave, I have get out and travel to the Demon World along time ago. \nHopefully someday, I can see my kin, to know how they look like. \nBut I rather stay here than to meet them and got reject..."
    p "..."
    "If it was [p] before he comes to this forest, he would think of Nine as weak and pathetic and force the demon to do what he wants. But now, he respects whatever choice Nine makes."
    p "I understand."
    n "..."
    "[p] moves his hand to Nine’s head. He wants to pat it but stops halfway."
    p "..."
    p " Nine!"
    n "What?"
    p "Thank you... for all ur helps. I was an ass to only said it till now."
    n "You are a good person [p]"
    p "(He says it again. This demon...)"
    "[p] leaves" 
    p "Live well Nine!"
    n "You too [p]"
    p "..."

    "[p] leaves the forest and return to a normal life. He travel from place to place, practices his skills. \nEven though [p] never act like he cares. He always helps people in need since that day." 

    "One day, in front of the market, he goes pass a big cart. The cart suddenly stops and an old man gets out “[p]!” The old man said."

    p "D-" 
    "[p] swallows his word. "
    p "My king, you shouldn’t show yourself here. It’s dangerous."
    k"I’m not a king anymore. Ren is. You don’t have to worry about that."
    p "..." 
    k "Ren had returned your title. Come and meet him sometimes." 
    p "..." 
    p "I will" 
    "The old man pats [p]’s shoulder. "
    p "..." 
    k "You have change my son. Much stronger, much more mature." 
    p "..." 
    p "You have change too dad. Much more chill." 
    k "I guess when leave power, people change for the better."
    p "..."
    k "Come [p], you look hungry. It had been ages since we eat together."
    p "It is."
    scene black with dissolve
    "END"
    call screen main_menu()
    
    