label morning_greet1:
    scene sit_up
    "Morning rolls around."
    show m
    show m_cockdown
    show m_m1
    "[p] looks around and sees [d] as soon as he wakes up."
    scene sit_up
    show m_tired
    show m_cockdown
    show m_blush
    show m_m2
    p "..."
    scene sit_up
    show m_surprise
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_open2
    d "Did you sleep well?"
    scene sit_up
    show m
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_normal
    p "..."
    scene sit_up
    show m_tired
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_open2
    p "Y-yes..."
    scene sit_up
    show m
    show m_cockdown
    show m_blush
    show m_shame
    show m_m2
    "[d] smiles."
    scene sit_up
    show m_tired
    show m_cockdown
    show m_blush
    show m_shame
    show m_m2
    p "..."
    d "Good boy."
    scene sit_up
    show m_close
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_open2
    p "..."
    $ene = 100
    jump simbutton2
label morning_greet2:
    scene sit_sad
    "Morning rolls around."
    show m
    show m_cockdown
    show m_m1
    "[p] wakes up and looks around to find [d]."
    scene sit_up
    show m_tired
    show m_cockdown
    show m_blush
    show m_m2
    p "..."
    scene sit_up
    show m_surprise
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_open2
    d "What are you looking at?"
    scene sit_up
    show m_surprise
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_normal
    p "!"
    scene sit_up
    show m
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_open2
    p "N-nothing..."
    scene sit_up
    show m_tired
    show m_cockdown
    show m_blush
    show m_shame
    show m_m2
    "[d] smiles."
    d "Okay."
    scene sit_up
    show m_close
    show m_cockdown
    show m_blush
    show m_shame
    show m_m2
    p "..."
    scene sit_up
    show m_tired
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_open2
    p "(What am I doing?)"
    $ene = 100
    jump simbutton2
label morning_greet3:
    scene sit_sad
    "Morning rolls around."
    show m
    show m_cockdown
    show m_m1
    p "..."
    scene sit_up
    show m_tired
    show m_cockdown
    show m_blush
    show m_m2
    d "What's wrong? Why did you look around like that?"
    scene sit_up
    show m_surprise
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_open2
    p "!"
    scene sit_up
    show m
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_open1
    p "N-Nothing"
    scene sit_up
    show m_tired
    show m_cockdown
    show m_blush
    show m_shame
    show m_m2
    "[p] looks away."
    scene sit_up
    show m_surprise
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_normal
    p "!"
    scene darkforest2
    show kiss_suprised
    p "M..."
    hide kiss_suprised
    show kiss_fast_short
    p "..."
    scene sit_up
    show m
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_open2
    p "P-Please don't do that again."
    scene sit_up
    show m_tired
    show m_cockdown
    show m_blush
    show m_shame
    show m_m1
    "[d] smiles."
    d "Would you prefer having sex with me?"
    scene sit_up
    show m_surprise
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_open2
    p "N-no..."
    scene sit_up
    show m_tired
    show m_cockdown
    show m_blush
    show m_shame
    show m_m
    d "If you don't want me to kiss you, don't avert your eyes. Do you hate my face that much?"
    scene sit_up
    show m_surprise
    show m_cockdown
    show m_blush
    show m_shame
    show m_m_open2
    p "I-..."
    hide m_m
    show m_m_open2
    scene sit_up
    show m_close
    show m_cockdown
    show m_blush
    show m_shame
    show m_m
    p "..."
    $ene = 100
    jump simbutton2
